In [1]:
from fastai.text.all import *
path = untar_data(URLs.IMDB)

dls = TextDataLoaders.from_folder(path, valid='test')
dls.show_batch()

In [2]:
learn = text_classifier_learner(dls,AWD_LSTM,drop_mult=0.5,metrics=accuracy)

In [3]:
learn.fine_tune(4,1e-2)

In [3]:
learn.show_results()

In [4]:
learn.predict("That movie was wicked cool !")

('pos', tensor(1), tensor([0.4265, 0.5735]))

In [6]:
# 在IMDb上微调语言模型
dls_lm = TextDataLoaders.from_folder(path,is_lm=True,vaild_pct=0.1)
dls_lm.show_batch(max_n=5)
learn1 = language_model_learner(dls_lm,AWD_LSTM,metrics=[accuracy,Perplexity()],path=path,wd=0.1).to_fp16()
learn1.fit_one_cycle(1,1e-2)

/usr/local/lib/python3.8/dist-packages/fastprogress/fastprogress.py:73: UserWarning: Your generator is empty.
  warn("Your generator is empty.")


In [7]:
learn1.save('1epoch')

Path('/root/.fastai/data/imdb/models/1epoch.pth')

In [11]:
# 模型最后一层将激活值转换为词表中每个单词的概率。除去模型最后一层，称之为编码器。
learn1 = learn1.load('1epoch')
learn1.unfreeze()
learn1.fit_one_cycle(10,1e-3)
learn1.save_encoder('finetuned')

/usr/local/lib/python3.8/dist-packages/fastprogress/fastprogress.py:73: UserWarning: Your generator is empty.
  warn("Your generator is empty.")
/usr/local/lib/python3.8/dist-packages/fastprogress/fastprogress.py:73: UserWarning: Your generator is empty.
  warn("Your generator is empty.")
/usr/local/lib/python3.8/dist-packages/fastprogress/fastprogress.py:73: UserWarning: Your generator is empty.
  warn("Your generator is empty.")


KeyboardInterrupt: ignored

## 编码器
编码器是模型的一部分，将输入文本映射成一些向量，通常用来解释具体的NLP任务。编码器本身并不特定于具体任务，通常与“编码器”或“头部”一起使用，后者用于将向量映射到某些特定任务设计的数据结构。

In [12]:
# 使用该模型生成随机评论
TEXT = "I liked this movie because"
N_WORDS = 40
N_SENTENCES = 2
preds = [learn1.predict(TEXT,N_WORDS,temperature=0.75) for _ in range(N_SENTENCES)]
print("\n".join(preds))

i liked this movie because i was not expecting a really good movie , so i wanted to watch it for the first time but do n't even expect any new language , but i found it to be excellent . It was a
i liked this movie because it was so good i wanted to go see it . But I 'm so addicted to Shakespeare and this movie was so good . My favorite part was with the Scorsese , which is


In [13]:
dls_clas=TextDataLoaders.from_folder(untar_data(URLs.IMDB),vaild='text',text_vocab=dls_lm.vocab)
learn2=text_classifier_learner(dls,AWD_LSTM,drop_mult=0.5,metrics=accuracy)
learn2=learn2.load_encoder('finetuned')


FileNotFoundError: ignored

In [ ]:
# 采用差异化学习率，逐步解冻
learn2.fit_one_cycle(1,2e-2)


In [ ]:
learn2.freeze_to(-2)
learn2.fit_one_cycle(1,slice(1e-2/(2.6**4),1e-2))

In [ ]:
learn2.freeze_to(-3)
learn2.fit_one_cycle(1,slice(5e-2/(2.6**4),5e-3))

In [ ]:
# 解冻整个模型
learn2.unfreeze()
learn2.fit_one_cycle(2,slice(1e-3/(2.6**4),1e-3))

## 使用Hugging Face系列库进行推理

In [17]:
import locale
def getpreferredencoding(do_setlocale = True):
    return "UTF-8"
locale.getpreferredencoding = getpreferredencoding

!pip install transformers
import torch
from transformers import GPT2Tokenizer,GPT2LMHeadModel

tokenizer = GPT2Tokenizer.from_pretrained('gpt2')

text = "With great power comes great "
indexed_tokens = tokenizer.encode(text)

tokens_tensor = torch.tensor([indexed_tokens])

Looking in indexes: https://pypi.org/simple, https://us-python.pkg.dev/colab-wheels/public/simple/


In [18]:
print(tokens_tensor)
print(indexed_tokens)

tensor([[3152, 1049, 1176, 2058, 1049,  220]])
[3152, 1049, 1176, 2058, 1049, 220]


In [20]:
# 加载模型权重
model = GPT2LMHeadModel.from_pretrained('gpt2')

model.eval()

with torch.no_grad():
  outputs= model(tokens_tensor)
  predictions = outputs[0]

predicted_index = torch.argmax(predictions[0,-1,:]).item()
predicted_text = tokenizer.decode(indexed_tokens + [predicted_index])

print(predicted_text)

With great power comes great ills


In [21]:
len(outputs)

2

In [22]:
outputs[0].shape

torch.Size([1, 6, 50257])

In [27]:
print(predictions)

tensor([[[ -32.9691,  -32.2417,  -35.0687,  ...,  -37.8427,  -38.3769,
           -32.6595],
         [ -88.2333,  -87.4561,  -94.1138,  ...,  -91.9931,  -95.2675,
           -90.7904],
         [ -62.1415,  -64.1625,  -72.3117,  ...,  -72.0955,  -71.1991,
           -66.7285],
         [ -94.2255,  -94.3511, -101.4683,  ..., -100.7295, -100.7159,
           -97.0163],
         [ -99.9127,  -99.7470, -106.7008,  ..., -106.1145, -109.8075,
          -102.8086],
         [ -57.2461,  -60.1474,  -63.3509,  ...,  -72.5494,  -69.3108,
           -61.1931]]])


In [26]:
print(predictions[0,-1,:])

tensor([-57.2461, -60.1474, -63.3509,  ..., -72.5494, -69.3108, -61.1931])


In [31]:
print(predictions[0,-1,:])

tensor([-57.2461, -60.1474, -63.3509,  ..., -72.5494, -69.3108, -61.1931])


In [32]:
torch.argmax(predictions[0,-1,:])

tensor(2171)

In [33]:
torch.argmax(predictions[0,-1,:]).item()

2171

In [34]:
tokenizer.decode([predicted_index])

'ills'

In [35]:
torch.argmax(predictions[0,1,:]).item()

1943

In [42]:
tokenizer.decode(torch.argmax(predictions[0,-1,:]).item())

'ills'

In [38]:
print(predicted_text)

With great power comes great ills
