In [92]:
import torch
from torch import tensor, dtype

In [93]:
torch.__version__

'1.11.0'

In [94]:
a = torch.tensor([1, 2, 3])

In [95]:
print(a)

tensor([1, 2, 3])


In [96]:
b = torch.tensor([[1, 2, 3], [4, 5, 6]])

In [97]:
print(b)

tensor([[1, 2, 3],
        [4, 5, 6]])


In [98]:
c = torch.zeros(3, 4)
d = torch.ones(3, 4)
e = torch.empty([3, 4])

In [99]:
print(c)
print(d)
print(e)

tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])
tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]])
tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])


In [100]:
f = torch.rand(3, 5)

In [101]:
print(f)

tensor([[0.2239, 0.8011, 0.3705, 0.8548, 0.0071],
        [0.3255, 0.9549, 0.5592, 0.7182, 0.3952],
        [0.1393, 0.9640, 0.8163, 0.5481, 0.8634]])


In [102]:
g = torch.randint(3, 10, (2, 2))
print(g)

tensor([[3, 5],
        [4, 7]])


In [103]:
x = torch.linspace(1, 50, 10)
print(x)

tensor([ 1.0000,  6.4444, 11.8889, 17.3333, 22.7778, 28.2222, 33.6667, 39.1111,
        44.5556, 50.0000])


In [104]:
y = torch.logspace(1, 50, 10)
print(y)

tensor([1.0000e+01, 2.7826e+06, 7.7426e+11, 2.1544e+17, 5.9948e+22, 1.6681e+28,
        4.6416e+33,        inf,        inf,        inf])


## Pytorch中tensor的属性

In [105]:
import numpy as np

a = torch.tensor(np.arange(1))
a.item()

0

In [106]:
f.__array__()

array([[0.22394097, 0.80109036, 0.37052786, 0.85481006, 0.00707829],
       [0.32548648, 0.95490915, 0.55919784, 0.71824396, 0.39516604],
       [0.13929796, 0.9640117 , 0.8162883 , 0.54808867, 0.863437  ]],
      dtype=float32)

In [107]:
w = f.numpy()
w

array([[0.22394097, 0.80109036, 0.37052786, 0.85481006, 0.00707829],
       [0.32548648, 0.95490915, 0.55919784, 0.71824396, 0.39516604],
       [0.13929796, 0.9640117 , 0.8162883 , 0.54808867, 0.863437  ]],
      dtype=float32)

In [108]:
f

tensor([[0.2239, 0.8011, 0.3705, 0.8548, 0.0071],
        [0.3255, 0.9549, 0.5592, 0.7182, 0.3952],
        [0.1393, 0.9640, 0.8163, 0.5481, 0.8634]])

In [109]:
f.dim()

2

In [110]:
a.dtype

torch.int32

In [111]:
f.shape

torch.Size([3, 5])

In [112]:
f.reshape(5, 3)

tensor([[0.2239, 0.8011, 0.3705],
        [0.8548, 0.0071, 0.3255],
        [0.9549, 0.5592, 0.7182],
        [0.3952, 0.1393, 0.9640],
        [0.8163, 0.5481, 0.8634]])

In [113]:
www = f.view(5, 3)
www

tensor([[0.2239, 0.8011, 0.3705],
        [0.8548, 0.0071, 0.3255],
        [0.9549, 0.5592, 0.7182],
        [0.3952, 0.1393, 0.9640],
        [0.8163, 0.5481, 0.8634]])

In [114]:
www

tensor([[0.2239, 0.8011, 0.3705],
        [0.8548, 0.0071, 0.3255],
        [0.9549, 0.5592, 0.7182],
        [0.3952, 0.1393, 0.9640],
        [0.8163, 0.5481, 0.8634]])

In [115]:
f

tensor([[0.2239, 0.8011, 0.3705, 0.8548, 0.0071],
        [0.3255, 0.9549, 0.5592, 0.7182, 0.3952],
        [0.1393, 0.9640, 0.8163, 0.5481, 0.8634]])

In [116]:
f.t()

tensor([[0.2239, 0.3255, 0.1393],
        [0.8011, 0.9549, 0.9640],
        [0.3705, 0.5592, 0.8163],
        [0.8548, 0.7182, 0.5481],
        [0.0071, 0.3952, 0.8634]])

In [117]:
f

tensor([[0.2239, 0.8011, 0.3705, 0.8548, 0.0071],
        [0.3255, 0.9549, 0.5592, 0.7182, 0.3952],
        [0.1393, 0.9640, 0.8163, 0.5481, 0.8634]])

In [118]:
wwww = f.t()
wwww

tensor([[0.2239, 0.3255, 0.1393],
        [0.8011, 0.9549, 0.9640],
        [0.3705, 0.5592, 0.8163],
        [0.8548, 0.7182, 0.5481],
        [0.0071, 0.3952, 0.8634]])

In [119]:
x = torch.tensor(np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]]))

In [120]:
x

tensor([[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]], dtype=torch.int32)

In [121]:
x.size()

torch.Size([3, 3])

In [124]:
x.permute(1, 0)

tensor([[1, 4, 7],
        [2, 5, 8],
        [3, 6, 9]], dtype=torch.int32)

In [127]:
a = torch.tensor([1, 2, 3])
a

tensor([1, 2, 3])

In [128]:
a.size()

torch.Size([3])

In [130]:
a.shape

torch.Size([3])

In [132]:
a.unsqueeze(0)

tensor([[1, 2, 3]])

In [133]:
a

tensor([1, 2, 3])

In [134]:
a.size()

torch.Size([3])

In [137]:
a.unsqueeze(0)

tensor([[1, 2, 3]])

In [140]:
a = torch.ones([2, 3], dtype=torch.int)
a

tensor([[1, 1, 1],
        [1, 1, 1]], dtype=torch.int32)

In [141]:
a = torch.randn(2,3,4)
a

tensor([[[ 0.5727, -0.8855, -0.2065, -0.4861],
         [-1.3608,  0.3056,  1.4112,  1.9345],
         [ 1.5481, -0.4564, -0.4827, -0.3279]],

        [[ 0.5326,  0.5156,  0.6665, -1.2862],
         [ 1.1651,  0.6465, -2.3773, -0.1092],
         [ 0.5883, -0.8583, -0.9948, -0.1798]]])

In [144]:
a[:,2:,2:]

tensor([[[-0.4827, -0.3279]],

        [[-0.9948, -0.1798]]])

In [145]:
a[:,2:,2:].size()

torch.Size([2, 1, 2])

In [146]:
a[:,2:,2:].reshape(1,4)

tensor([[-0.4827, -0.3279, -0.9948, -0.1798]])

In [147]:
device = torch.device("cuda:0" if torch.cuda.is_available() else "cpu")

In [148]:
device

device(type='cuda', index=0)

In [150]:
if torch.cuda.is_available():
    device = torch.device("cuda")
    y = torch.ones_like(x,device=device)
    x = x.to(device)
    z = x+y
    print(z)
    print(z.to("cpu",torch.double))

tensor([[ 2,  3,  4],
        [ 5,  6,  7],
        [ 8,  9, 10]], device='cuda:0', dtype=torch.int32)
tensor([[ 2.,  3.,  4.],
        [ 5.,  6.,  7.],
        [ 8.,  9., 10.]], dtype=torch.float64)


In [151]:
a = torch.randn(3,4)
a

tensor([[-0.9965, -0.4366,  0.4791, -0.2910],
        [ 1.4603, -0.1381,  2.9519,  1.4359],
        [ 0.1943,  1.7078, -0.6070, -0.0519]])

In [152]:
a.max()

tensor(2.9519)

In [153]:
a.max(dim=0)

torch.return_types.max(
values=tensor([1.4603, 1.7078, 2.9519, 1.4359]),
indices=tensor([1, 2, 1, 1]))

In [154]:
a.max(dim=0)[0]

tensor([1.4603, 1.7078, 2.9519, 1.4359])

In [155]:
a.max(dim=0)[1]

tensor([1, 2, 1, 1])

In [156]:
a.mean()

tensor(0.4757)

In [157]:
a.min()

tensor(-0.9965)

In [158]:
a.argmax()

tensor(6)

In [159]:
a.argmin()

tensor(0)

In [160]:
a.abs()

tensor([[0.9965, 0.4366, 0.4791, 0.2910],
        [1.4603, 0.1381, 2.9519, 1.4359],
        [0.1943, 1.7078, 0.6070, 0.0519]])

In [161]:
a.median()

tensor(-0.0519)