In [1]:
import torch

x = torch.ones(2, 2, requires_grad=True)

In [2]:
x

tensor([[1., 1.],
        [1., 1.]], requires_grad=True)

In [3]:
y = x + 2
y

tensor([[3., 3.],
        [3., 3.]], grad_fn=<AddBackward0>)

In [5]:
z = 3 * y * y
z

tensor([[27., 27.],
        [27., 27.]], grad_fn=<MulBackward0>)

In [6]:
out = z.mean()

In [7]:
out.item()

27.0

In [8]:
out

tensor(27., grad_fn=<MeanBackward0>)

In [9]:
print(y.grad_fn)

In [10]:
print(y.requires_grad)

True


In [11]:
with torch.no_grad():
    w = (x * x).sum()
print(w.requires_grad)

False


In [15]:
a = torch.randn(2, 2, requires_grad=False)
a

tensor([[-0.4938, -1.6681],
        [-2.2497, -1.6601]])

In [17]:
a = (a * 2 - 1) / (a - 3)
a

tensor([[-0.0567, -0.4142],
        [-0.5609, -0.4120]])

In [18]:
print(a.requires_grad)

False


In [19]:
a.requires_grad_(True)

tensor([[-0.0567, -0.4142],
        [-0.5609, -0.4120]], requires_grad=True)

In [21]:
b = (a * a).sum()
b

tensor(0.6591, grad_fn=<SumBackward0>)

In [23]:
with torch.no_grad():
    c = b * b

In [25]:
print(c.requires_grad)
c

False


tensor(0.4345)

In [26]:
c.data

tensor(0.4345)

In [27]:
print(b.requires_grad)
b.data

True


tensor(0.6591)

In [28]:
c1 = c.numpy()
c1

array(0.4344513, dtype=float32)

In [30]:
c2 = b.detach().numpy()
c2

array(0.6591292, dtype=float32)